#!/bin/bash
#
# Cutie-Pi Dashboard Installer
# A pixel-art Pi-hole dashboard for small LCD screens
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Default values
INSTALL_DIR="/opt/cutie-pi"
CONFIG_FILE="/etc/cutie-pi/config"
SERVICE_FILE="/etc/systemd/system/cutie-pi.service"
FONT_DIR="$HOME/.fonts"

# Configuration defaults
DEFAULT_PIHOLE_API="http://localhost/api"
DEFAULT_PIHOLE_PASSWORD=""
DEFAULT_SCREEN_WIDTH="480"
DEFAULT_SCREEN_HEIGHT="320"

echo -e "${CYAN}"
echo "  ██████╗██╗   ██╗████████╗██╗███████╗      ██████╗ ██╗"
echo " ██╔════╝██║   ██║╚══██╔══╝██║██╔════╝      ██╔══██╗██║"
echo " ██║     ██║   ██║   ██║   ██║█████╗  █████╗██████╔╝██║"
echo " ██║     ██║   ██║   ██║   ██║██╔══╝  ╚════╝██╔═══╝ ██║"
echo " ╚██████╗╚██████╔╝   ██║   ██║███████╗      ██║     ██║"
echo "  ╚═════╝ ╚═════╝    ╚═╝   ╚═╝╚══════╝      ╚═╝     ╚═╝"
echo -e "${NC}"
echo "Pixel-art Pi-hole Dashboard"
echo "============================================"
echo ""

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: This script must be run as root${NC}"
   echo "Please run: sudo bash install.sh"
   exit 1
fi

# Get the actual user (not root)
ACTUAL_USER="${SUDO_USER:-$USER}"
ACTUAL_HOME=$(getent passwd "$ACTUAL_USER" | cut -d: -f6)
FONT_DIR="$ACTUAL_HOME/.fonts"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --pihole-password)
            PIHOLE_PASSWORD="$2"
            shift 2
            ;;
        --pihole-api)
            PIHOLE_API="$2"
            shift 2
            ;;
        --screen-width)
            SCREEN_WIDTH="$2"
            shift 2
            ;;
        --screen-height)
            SCREEN_HEIGHT="$2"
            shift 2
            ;;
        --help)
            echo "Usage: sudo bash install.sh [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --pihole-password PASSWORD   Pi-hole API password"
            echo "  --pihole-api URL             Pi-hole API URL (default: http://localhost/api)"
            echo "  --screen-width WIDTH         Screen width in pixels (default: 480)"
            echo "  --screen-height HEIGHT       Screen height in pixels (default: 320)"
            echo "  --help                       Show this help message"
            echo ""
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

# Set defaults if not provided
PIHOLE_API="${PIHOLE_API:-$DEFAULT_PIHOLE_API}"
PIHOLE_PASSWORD="${PIHOLE_PASSWORD:-$DEFAULT_PIHOLE_PASSWORD}"
SCREEN_WIDTH="${SCREEN_WIDTH:-$DEFAULT_SCREEN_WIDTH}"
SCREEN_HEIGHT="${SCREEN_HEIGHT:-$DEFAULT_SCREEN_HEIGHT}"

echo -e "${GREEN}[1/6]${NC} Installing system dependencies..."
apt-get update -qq
apt-get install -y -qq python3 python3-pygame python3-requests xserver-xorg xinit fonts-dejavu > /dev/null

echo -e "${GREEN}[2/6]${NC} Verifying Python dependencies..."
python3 -c "import pygame, requests" 2>/dev/null || {
    echo -e "${RED}Error: Python dependencies not installed correctly${NC}"
    exit 1
}

echo -e "${GREEN}[3/6]${NC} Installing pixel font..."
mkdir -p "$FONT_DIR"
if [[ ! -f "$FONT_DIR/PressStart2P.ttf" ]]; then
    echo "Downloading Press Start 2P font..."
    curl -sL "https://github.com/google/fonts/raw/main/ofl/pressstart2p/PressStart2P-Regular.ttf" \
        -o "$FONT_DIR/PressStart2P.ttf"
    chown "$ACTUAL_USER:$ACTUAL_USER" "$FONT_DIR/PressStart2P.ttf"
fi

echo -e "${GREEN}[4/6]${NC} Installing cutie-pi..."
# Create installation directory
mkdir -p "$INSTALL_DIR"

# Copy application files
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cp -r "$SCRIPT_DIR"/*.py "$INSTALL_DIR/" 2>/dev/null || true
cp -r "$SCRIPT_DIR"/api "$INSTALL_DIR/"
cp -r "$SCRIPT_DIR"/screens "$INSTALL_DIR/"
cp -r "$SCRIPT_DIR"/ui "$INSTALL_DIR/"
cp -r "$SCRIPT_DIR"/utils "$INSTALL_DIR/"

# Set permissions
chmod -R 755 "$INSTALL_DIR"

echo -e "${GREEN}[5/6]${NC} Creating configuration..."
# Create config directory
mkdir -p /etc/cutie-pi

# Write configuration file
cat > "$CONFIG_FILE" << EOF
# Cutie-Pi Configuration
# Generated by installer on $(date)

# Pi-hole API settings
CUTIE_PIHOLE_API="$PIHOLE_API"
CUTIE_PIHOLE_PASSWORD="$PIHOLE_PASSWORD"

# Display settings
CUTIE_SCREEN_WIDTH="$SCREEN_WIDTH"
CUTIE_SCREEN_HEIGHT="$SCREEN_HEIGHT"
CUTIE_FPS="30"

# Update intervals (seconds)
CUTIE_API_INTERVAL="5"
CUTIE_SYSTEM_INTERVAL="2"

# Swipe detection threshold
CUTIE_SWIPE_THRESHOLD="50"
EOF

chmod 600 "$CONFIG_FILE"

echo -e "${GREEN}[6/6]${NC} Setting up systemd service..."

# Configure Xwrapper to allow anybody to run X server
if [[ -f /etc/X11/Xwrapper.config ]]; then
    sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
else
    mkdir -p /etc/X11
    echo "allowed_users=anybody" > /etc/X11/Xwrapper.config
fi

# Create systemd service
cat > "$SERVICE_FILE" << EOF
[Unit]
Description=Cutie-Pi Dashboard
After=network.target pihole-FTL.service
Wants=pihole-FTL.service

[Service]
Type=simple
User=$ACTUAL_USER
EnvironmentFile=$CONFIG_FILE
ExecStart=/usr/bin/xinit /usr/bin/python3 $INSTALL_DIR/main.py -- :0 -nocursor
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

# Reload systemd and enable service
systemctl daemon-reload
systemctl enable cutie-pi.service

echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}Installation complete!${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo "Configuration file: $CONFIG_FILE"
echo "Installation directory: $INSTALL_DIR"
echo ""
echo "Commands:"
echo "  Start dashboard:   sudo systemctl start cutie-pi"
echo "  Stop dashboard:    sudo systemctl stop cutie-pi"
echo "  View logs:         sudo journalctl -u cutie-pi -f"
echo "  Edit config:       sudo nano $CONFIG_FILE"
echo ""
echo -e "${YELLOW}Note: You may need to configure your Pi-hole password in:${NC}"
echo -e "${YELLOW}      $CONFIG_FILE${NC}"
echo ""
echo "Start now with: sudo systemctl start cutie-pi"
echo ""
